runtime: go119
instance_class: B1
service: default
env: standard
app_engine_apis: true

env_variables:
  PORT: 8000
  JWT_SECRET: "secret"
  DB_HOST: "/cloudsql/<DB_CONN_CLOUDSQL>"
  DB_USER: "postgres"
  DB_PASSWORD: "root"
  DB_NAME: "template"
  DB_SSL: "disable"
  DB_CONN: "cloudsql"
  DB_TYPE: "POSTGRESQL"
  MIGRATION_KEY: "key"
  MIGRATION_HEADER: "header"

automatic_scaling:
  max_instances: 3
  min_instances: 1
  max_idle_instances: 2
  min_idle_instances: 1
  max_concurrent_requests: 50
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8
  min_pending_latency: 500ms

beta_settings:
  cloud_sql_instances: "/cloudsql/<DB_CONN_CLOUDSQL>"
